### PR TITLE
#168190297 Integrate redis server on heroku app and docker

### PR DESCRIPTION
**Pull request by dinorhythms**
#### What does this PR do?
This PR integrate Redis Server on Heroku app
#### Description of Task to be completed?
- create hereko redis addon on heroku
- create redis url env
- create redis config file
- test the heroku redis
- add redis image to docker-compose.yml
#### How should this be manually tested?
- It can be tested on heroku app with logout functionality
#### What are the relevant pivotal tracker stories?
[#168190297](https://www.pivotaltracker.com/story/show/168190297)

### CODE REVIEW

**Review by Mcdavid95 — APPROVED** [review]
LGTM

**Comment by tejiri4** [comment]
Add redis configuration to the docker.compose.yml file

**Comment by dinorhythms** [comment]
> Add redis configuration to the docker.compose.yml file

**Comment by tejiri4** [comment]
Nice job hope you added the redis URL to heroku?

**Comment by dinorhythms** [comment]
> Nice job hope you added the redis URL to heroku?

yes heroku redis as been added and it works in production only

**Review by tejiri4 — APPROVED** [review]
LGTM

**Pull request merged**
