### PR TITLE
#168094076 moving models folder to src

### PR DESCRIPTION
**Pull request by komsic**
#### What this PR does
This PR move models folder to src folder to enable Regle tracking

#### Tasks completed
- rename eslint config file
- move models folder to src folder

#### How this can be manually tested
- Clone this branch
- Change directory into it
- Check the src folder for the models folder

#### What are the relevant pivotal tracker stories?
[#168094076](https://www.pivotaltracker.com/story/show/168094076)

### CODE REVIEW

**Review by Mcdavid95 — COMMENTED** [review]
check the `.hound.yml` file and also change the eslint file path there to fix the hound errors

**Comment by tejiri4** [comment]
Rebase your branch with develop

**Comment by komsic** [comment]
> check the `.hound.yml` file and also change the eslint file path there to fix the hound errors

Done

**Comment by komsic** [comment]
> Rebase your branch with develop

Done

**Pull request merged**
