### PR TITLE
#167727743 user should be able to delete comments they made

### PR DESCRIPTION
**Pull request by ladaposamuel**
#### What does this PR do?
This PR will enable users to have access to deleting their comments

#### Description of Task to be completed?
- created patch routes
- update model and migration with status
- create a delete(update) function in the controller
- wrote tests to affirm feature

#### How should this be manually tested?
- CLONE this repo
- open the cloned directory
- run `npm start:dev`
- access the docs using `{base-url}/docs`
- delete a comment using `{base-url}comments/{comment-id}`

#### What are the relevant pivotal tracker stories?
[#167727743](https://www.pivotaltracker.com/story/show/167727743)

### CODE REVIEW

**Comment by tejiri4** [comment]
Try your PR on heroku using the review app and add a label if your endpoint is working on heroku

**Comment by ladaposamuel** [comment]
> Try your PR on heroku using the review app and add a label if your endpoint is working on heroku

The route is returning a 404 on heroku.

**Comment by tejiri4** [comment]
let wait for @kola to set up logger so you can see the response body clearly in the heroku log. sync with him to make it faster

**Comment by tejiri4** [comment]
Check your heroku log but first rebase with develop

**Comment by ladaposamuel** [comment]
> Check your heroku log but first rebase with develop

Will do, Thanks

**Comment by ladaposamuel** [comment]
I couldn't test on Heroku because of the `DOC_BASE_URL` issue, 

after setting the `DOC_BASE_URL` to my own PR staged URL I got this error while attempting to sign in

```
{
  "status": "error",
  "data": {
    "error": "relation \"Users\" does not exist"
  }
}
```

**Comment by tejiri4** [comment]
> I couldn't test on Heroku because of the `DOC_BASE_URL` issue,
> 
> after setting the `DOC_BASE_URL` to my own PR staged URL I got this error while attempting to sign in
> 
> ```
> {
>   "status": "error",
>   "data": {
>     "error": "relation \"Users\" does not exist"
>   }
> }
> ```

You need to migrate and seed your review app heroku posgres addons . Get your credentials and seed or sync with jude or kazeem

**Comment by ladaposamuel** [comment]
> > I couldn't test on Heroku because of the `DOC_BASE_URL` issue,
> > after setting the `DOC_BASE_URL` to my own PR staged URL I got this error while attempting to sign in
> > 
> >   
> >     
> >       
> >     
> >   ```
> > {
> >   "status": "error",
> >   "data": {
> >     "error": "relation \"Users\" does not exist"
> >   }
> > }
> > ```
> 
> You need to migrate and seed your review app heroku posgres addons . Get your credentials and seed or sync with jude or kazeem

Thanks for the update, does this mean each time I want to test on heroku I need to update the `DOC_BASE_URL` variable?

**Comment by tejiri4** [comment]
Rebase your branch with develop and checks if it works now

**Review by tejiri4 — APPROVED** [review]
LGTM

**Pull request merged**
